views:
  - name: product_analysis
    description: View containing transactions 360 degree information
    public: true
    meta:
      export_to_iris: true
      iris:
        timeseries: products.launchdate
        available_time_zones:
          - America/Los_Angeles
          - America/Chicago
          - America/New_York
          - Europe/London
          - Europe/Paris
          - Asia/Jerusalem
          - Europe/Moscow
          - Asia/Kolkata
          - Asia/Shanghai
          - Asia/Tokyo
          - Australia/Sydney

    tables:

      - join_path: products
        prefix: true
        includes:
          - productname
          - productcategory
          - designername
          - productid
          - launchdate
          - total_products
          - price          
          - cost
          - average_margin
          - average_price          
          - subcategory
          
        



