views:
  - name: transaction_analysis
    description: View containing transactions 360 degree information
    public: true
    meta:
      export_to_iris: true
      iris:
        timeseries: transactions.transaction_date
        available_time_zones:
          - America/Los_Angeles
          - America/Chicago
          - America/New_York
          - Europe/London
          - Europe/Paris
          - Asia/Jerusalem
          - Europe/Moscow
          - Asia/Kolkata
          - Asia/Shanghai
          - Asia/Tokyo
          - Australia/Sydney

    tables:
      - join_path: transactions
        prefix: true
        includes:
          - total_transactions
          - transaction_id
          - total_revenue
          - transaction_amount
          - average_transaction_amount
          - transaction_date
          - order_id
          - payment_method
          - transaction_type
          - skuid
          - discount_applied
          - discounted_amount
          - customer_id

      - join_path: products
        prefix: true
        includes:
          - productname
          - productcategory
          - designername
          - productid

      # - join_path: channel
      #   prefix: true
      #   includes:
      #     - store_name
      #     - channel_type
      #     - total_stores
        

